import { Link } from "react-router-dom";

function Home() {
  return (
      <div className="hero-bg">

            <div className="grid-overlay"></div>

                  <div className="glow glow1"></div>
                        <div className="glow glow2"></div>

                              <div className="hero-container">

                                      <div className="hero-logo">
                                                <div className="logo-ring"></div>
                                                          <div className="logo-core">RN</div>
                                                                  </div>

                                                                          <span className="hero-tag">
                                                                                    NEXT GENERATION AI PLATFORM
                                                                                            </span>

                                                                                                    <h1 className="hero-title">
                                                                                                              RiyadNova AI
                                                                                                                      </h1>

                                                                                                                              <h2 className="hero-subtitle">
                                                                                                                                        Transform Ideas Into Intelligent Businesses
                                                                                                                                                </h2>

                                                                                                                                                        <p className="hero-description">
                                                                                                                                                                  منصة ذكاء اصطناعي احترافية تساعد رواد الأعمال والطلاب
                                                                                                                                                                            على تحليل الأفكار، تقييم المشاريع، بناء النماذج التجارية،
                                                                                                                                                                                      واتخاذ قرارات ذكية اعتمادًا على أحدث تقنيات الذكاء الاصطناعي.
                                                                                                                                                                                              </p>

                                                                                                                                                                                                      <div className="hero-buttons">

                                                                                                                                                                                                                <Link to="/login">
                                                                                                                                                                                                                            <button className="btn-primary">
                                                                                                                                                                                                                                          تسجيل الدخول
                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                </Link>

                                                                                                                                                                                                                                                                          <Link to="/register">
                                                                                                                                                                                                                                                                                      <button className="btn-secondary">
                                                                                                                                                                                                                                                                                                    إنشاء حساب
                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                          </Link>

                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                          <div className="quick-grid">

                                                                                                                                                                                                                                                                                                                                                    <Link to="/dashboard" className="feature-card">

                                                                                                                                                                                                                                                                                                                                                                <div className="feature-icon">
                                                                                                                                                                                                                                                                                                                                                                              📊
                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                      <h3>Dashboard</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                  <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                لوحة تحكم ذكية تعرض كل بيانات مشروعك.
                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Link to="/idea-analyzer" className="feature-card">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="feature-icon">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          🧠
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3>Idea Analyzer</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            تحليل احترافي للأفكار باستخدام الذكاء الاصطناعي.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link to="/profile" className="feature-card">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="feature-icon">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      👤
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3>Profile</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        إدارة الحساب والملف الشخصي.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Link to="/settings" className="feature-card">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="feature-icon">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ⚙️
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3>Settings</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    تخصيص المنصة وإعدادات النظام.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default Home;